### ISSUE TITLE
is it possible to use fileLogger() and logger() at the same time?

### ISSUE THREAD

**Issue by imkarimkarim** [bogeychan/elysia-logger#10]

**Comment by bogeychan** [comment]
Hi 👋

Yes! It should be possible to do something like this:

```ts
import { Elysia } from 'elysia';
import { logger, fileLogger } from '@bogeychan/elysia-logger';

const app = new Elysia()
  .use(
    fileLogger({
      file: './out.log'
    }).decorate(({ log, ...rest }) => ({ fileLogger: log, ...rest }))
  )
  .use(logger())
  .get('/', (ctx) => {
    ctx.fileLogger.error('file error');
    ctx.log.error('error');
  })
  .listen(8080);

console.log(`http://${app.server!.hostname}:${app.server!.port}`);
```

_However, it somehow does not work with the latest elysia version: https://github.com/elysiajs/elysia/issues/291_

---

As a workaround you could use a logger "global", e.g:

```ts
import { Elysia } from 'elysia';
import { fileLogger, createPinoLogger } from '@bogeychan/elysia-logger';

const logger = createPinoLogger({
  level: 'error'
  // ...
});

const app = new Elysia()
  .use(
    fileLogger({
      file: './out.log'
    })
  )
  .get('/', (ctx) => {
    ctx.log.error('file error'); // <- fileLogger
    logger.error('error');
  })
  .listen(8080);

console.log(`http://${app.server!.hostname}:${app.server!.port}`);
```

**Comment by imkarimkarim** [comment]
thanks for the response
for now i will continue with fileLogger
it's get the job done

**Comment by imkarimkarim** [comment]
> Hi 👋
> 
> Yes! It should be possible to do something like this:
> 
> ```ts
> import { Elysia } from 'elysia';
> import { logger, fileLogger } from '@bogeychan/elysia-logger';
> 
> const app = new Elysia()
>   .use(
>     fileLogger({
>       file: './out.log'
>     }).decorate(({ log, ...rest }) => ({ fileLogger: log, ...rest }))
>   )
>   .use(logger())
>   .get('/', (ctx) => {
>     ctx.fileLogger.error('file error');
>     ctx.log.error('error');
>   })
>   .listen(8080);
> 
> console.log(`http://${app.server!.hostname}:${app.server!.port}`);
> ```
> 
> _However, it somehow does not work with the latest elysia version: [elysiajs/elysia#291](https://github.com/elysiajs/elysia/issues/291)_
> 
> As a workaround you could use a logger "global", e.g:
> 
> ```ts
> import { Elysia } from 'elysia';
> import { fileLogger, createPinoLogger } from '@bogeychan/elysia-logger';
> 
> const logger = createPinoLogger({
>   level: 'error'
>   // ...
> });
> 
> const app = new Elysia()
>   .use(
>     fileLogger({
>       file: './out.log'
>     })
>   )
>   .get('/', (ctx) => {
>     ctx.log.error('file error'); // <- fileLogger
>     logger.error('error');
>   })
>   .listen(8080);
> 
> console.log(`http://${app.server!.hostname}:${app.server!.port}`);
> ```

thanks for the response
for now i will continue with fileLogger
it's get the job done

**Comment by PawaOx4th** [comment]
Can you recommend how to use it in the `Apollo GraphQL` plugin ?
🙏🏻

**Comment by bogeychan** [comment]
@imkarimkarim, I published a fix to support your use case. You need to update the plugin to at least `0.0.13`.

I added 2 new examples:

- https://github.com/bogeychan/elysia-logger/blob/3ce246b20aaa29a6727cf14ea7b5d0cb46af7cde/examples/both.ts#L4
- https://github.com/bogeychan/elysia-logger/blob/3ce246b20aaa29a6727cf14ea7b5d0cb46af7cde/examples/multistream.ts#L4

**Comment by imkarimkarim** [comment]
> @imkarimkarim, I published a fix to support your use case. You need to update the plugin to at least `0.0.13`.
> 
> Use
> 
> ```ts
> fileLogger({
>     file: './out.log'
> }).derive(({ log, ...rest }) => ({ fileLogger: log, ...rest }))
> ```
> 
> instead of:
> 
> ```ts
> fileLogger({
>     file: './out.log'
> }).decorate(({ log, ...rest }) => ({ fileLogger: log, ...rest }))
> ```
> 
> i mixed `derive` and `decorate` up 😅
> 
> I added 2 new examples:
> 
>     * https://github.com/bogeychan/elysia-logger/blob/3ce246b20aaa29a6727cf14ea7b5d0cb46af7cde/examples/both.ts#L4
> 
>     * https://github.com/bogeychan/elysia-logger/blob/3ce246b20aaa29a6727cf14ea7b5d0cb46af7cde/examples/multistream.ts#L4

thanks for your time
it tried it but unfortunately now changes
here is my code: https://github.com/imkarimkarim/ElysiaJS-todo-app/blob/446b82c6b320c627383f1fe7f69b02dc9227ca92/src/app.ts#L14

**Comment by bogeychan** [comment]
Take a look at this example over here https://github.com/bogeychan/elysia-logger/blob/3ce246b20aaa29a6727cf14ea7b5d0cb46af7cde/examples/multistream.ts#L4

If this doesn't solve your problem, please try to give me a better description of your use case with an example
