### ISSUE TITLE
Property 'logger' does not exist on type 'Context

### ISSUE THREAD

**Issue by fruity4pie** [bogeychan/elysia-logger#2]
<img width="536" alt="image" src="https://github.com/bogeychan/elysia-logger/assets/15814446/aac44773-151c-4e48-b2e9-d2406e817b9c">

Property 'logger' does not exist on type 'Context<{ body: unknown; params: Record<never, string>; query: undefined; headers: undefined; response: unknown; }, {}> & { jwt: { readonly sign: (morePayload: Record<string, string> & JWTPayloadSpec) => Promise<...>; readonly verify: (jwt?: string | undefined) => Promise<...>; }; unsignCookie: (value: string) => { ...'.ts(2339)

**Comment by bogeychan** [comment]
Hi, thanks for your feedback! Should be fixed in version `0.0.6`.

Let me know if there is anything else.
