### ISSUE TITLE
Rename `onResponse` to `onAfterResponse` (breaking change in Elysia 1.1)

### ISSUE THREAD

**Issue by kimjisena** [bogeychan/elysia-logger#20]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@bogeychan/elysia-logger@0.0.22` for the project I'm working on.

The latest version of Elysia renamed the lifecycle method `onResponse` to `onAfterResponse`

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@bogeychan/elysia-logger/src/index.ts b/node_modules/@bogeychan/elysia-logger/src/index.ts
index de71b96..11912dd 100644
--- a/node_modules/@bogeychan/elysia-logger/src/index.ts
+++ b/node_modules/@bogeychan/elysia-logger/src/index.ts
@@ -114,7 +114,7 @@ function into(this: Logger, options: ElysiaLoggerOptions = {}) {
       .onRequest((ctx) => {
         ctx.store = { ...ctx.store, startTime: performance.now() };
       })
-      .onResponse({ as: "global" }, (ctx) => {
+      .onAfterResponse({ as: "global" }, (ctx) => {
         const log = getLog(ctx);
 
         if (log.level == "silent") {
```

Let me if know if I should open a PR to fix this issue.

**Comment by kimjisena** [comment]
actually, i just noticed there's a new version of `elysia-logger`

for anyone coming here you should just upgrade to the latest version(`0.1.1` as of the writing of this comment).

i do not plan to migrate yet so i'm sticking with `^0.0.22` and this patch.

again, appreciate the good work the author has done on this project.

**Comment by bogeychan** [comment]
Hi 👋

Thank you for tracking this issue down and reporting it!

I don't currently plan to support older versions of `elysia`, but I am considering making one (`LTS`) for version 1 when version 2 (major) is released.

You'll have to stick with `0.0.22` for now
