### ISSUE TITLE
Allow customizing non-error log level

### ISSUE THREAD

**Issue by andriygm** [bogeychan/elysia-logger#24]
### What is the problem this feature would solve?

Currently, info level is used for non-errors, but these logs occur very frequently when constantly serving client requests like for a web app and can bury other logs at different levels.

### What is the feature you are proposing to solve the problem?

Support defining a `requestLogLevel` parameter or similar so that it can be set to "debug" (or other levels, but debug is the big one).

**Comment by bogeychan** [comment]
Just published a new version, `0.1.5`. You can now use the new `useLevel` option to adjust the level:

https://github.com/bogeychan/elysia-logger/blob/12f00ecfbca8149d1e34bcbc08391f70c2186e36/examples/use-level.ts#L7-L10
