### ISSUE TITLE
Property 'log' does not exist on type

### ISSUE THREAD

**Issue by fruity4pie** [bogeychan/elysia-logger#3]
Why isn't it available in onError middleware? Is it the logger or Elysia problem? Could you maybe give an advice on how to handle errors globally?

Version: **0.0.6**

<img width="346" alt="image" src="https://github.com/bogeychan/elysia-logger/assets/15814446/b92aa432-3384-45bd-a564-d1b57b5d94e2">

<img width="596" alt="image" src="https://github.com/bogeychan/elysia-logger/assets/15814446/c17d9bab-17de-4e1a-be8e-7a8ffacc20d0">

Property 'log' does not exist on type '{ request: Request; code: "UNKNOWN"; error: Readonly<Error>; set: { headers: { [header: string]: string; } & { "Set-Cookie"?: string | string[] | undefined; }; status?: number | undefined; redirect?: string | undefined; }; } | { ...; } | { ...; } | { ...; } | { ...; }'.
  Property 'log' does not exist on type '{ request: Request; code: "UNKNOWN"; error: Readonly<Error>; set: { headers: { [header: string]: string; } & { "Set-Cookie"?: string | string[] | undefined; }; status?: number | undefined; redirect?: string | undefined; }; }'.ts(2339)

**Comment by bogeychan** [comment]
Hi, Elysia does not provide a way to pass plugins to hooks like Error. (you can open an issue on [elysia](https://github.com/elysiajs/elysia) itself for this purpose)

As a workaround, you can do something like:

```ts
import { createPinoLogger } from '@bogeychan/elysia-logger';

const log = createPinoLogger();

app.onError((ctx) => {
  log.error(ctx, ctx.error.name);
  return 'onError';
})
```

I made some small fixes in this regard in version `0.0.7`

After updating you can take a look at the whole examples here:

- [basic onError](https://github.com/bogeychan/elysia-logger/blob/master/examples/on-error.ts)
- or [onError with custom context](https://github.com/bogeychan/elysia-logger/blob/master/examples/on-error-with-context.ts)
