### ISSUE TITLE
Default Logging for all HTTP requests

### ISSUE THREAD

**Issue by mmadson** [bogeychan/elysia-logger#6]
My expectation, considering this is a plugin specifically for Elysia is that this would do request and/or response logging by default. Something similar to https://github.com/pinojs/pino-http. It seems that this mostly just exposes a pino logger on the request context. Not a bad start by any means but if you do have the time / energy a nice enhancement would be to support additional options for auto logging requests and responses ideally with some configuration for suppressing variables or redacting sensitive parts of the request / response. Thanks!

**Comment by bogeychan** [comment]
Thanks for your suggestion, it has already been implemented (available for several versions). feel free to open a new issue if there's anything else you'd like to see as a feature.
