### ISSUE TITLE
After update Elysia 0.7.18 Type error.

### ISSUE THREAD

**Issue by armada45-pixel** [bogeychan/elysia-logger#9]
Error
No overload matches this call.
  The last overload gave the following error.
    Argument of type '_INTERNAL_ElysiaLoggerPlugin<_INTERNAL_ElysiaLoggerPluginAutoLoggingState>' is not assignable to parameter of type 'Promise<{ default: Elysia<any, any, any, any, any, any>; }>'.ts(2769)
index.d.ts(392, 5): The last overload is declared here.
(alias) logger(options?: _INTERNAL_ElysiaLoggerPluginAutoLoggingEnabledOptions<StreamLoggerOptions> | undefined): _INTERNAL_ElysiaLoggerPlugin<...> (+1 overload)
import logger
The StreamLogger is used to write log entries to a stream such as the console output (default behavior).

```ts
import { Elysia } from "elysia"
import { logger } from "@bogeychan/elysia-logger"

const app = new Elysia().use(logger()).listen(8081)

console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`)
```

![image](https://github.com/bogeychan/elysia-logger/assets/59261678/12fa7ae5-ca1e-4c13-8d70-45b672134d31)

**Comment by armada45-pixel** [comment]
I fix this error by remove overload type at https://github.com/bogeychan/elysia-logger/blob/master/src/index.ts#L32-L37

and rebuild package.

**Comment by bogeychan** [comment]
Hi 👋

thanks for reporting! I can't reproduce it on my end.

- you can try to `bun upgrade` and `bun init -y` a fresh project
- make sure to use `typescript >= 5.0.0`
- reload your `vscode` window / typescript server after install.

**Comment by armada45-pixel** [comment]
Work!!!
```bash
rm -fr ~/.bun/install/cache && bun install
````

**Comment by armada45-pixel** [comment]
After update to 0.7.20
Everyplugin type error
Restart vsocde not working.
So delete node_modules ,bun.lockb
bun cache.
And install package.

```bash
rm node_modules -rf
rm bun.lockb
rm -fr ~/.bun/install/cache
bun i
```
